/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package th.co.geniustree.google.cloudprint.api.model;

import com.google.gson.Gson;
import java.util.List;

/**
 *
 * @author jittagorn pitakmetagoon
 * @reference
 * https://developers.google.com/cloud-print/docs/appInterfaces#submit
 */
public class SubmitJob {
    /*
     * - printerid
     * Unique printer identification (generated by Google Cloud Print). To get valid printer IDs for a given user, retrieve the list of available printers for that Google Account by querying the /search service interface.
     */

    private String printerId;
    /*
     * - title
     * Title of the print job, to be used within GCP.
     */
    private String title;
    /*
     * - capabilities
     * Printer capabilities (XPS or PPD). Each GCP printer has, associated with it, a list of pair-value capabilities representing printer-specific attributes (available printing formats, copy count, etc.) Capabilities for a given printer can be retrieved using the /list service interface. These retrieved capabilities can then be used to specify desired options on the print job (for instance, print 5 copies instead of the default 1, or print duplex instead of single sided).
     */
    //private String capabilities;
    private Ticket ticket;
    /*
     * - content
     * Document to print.
     */
    private byte[] content;
    /*
     * -contentType
     * Document type. Currently, valid document types are: url, application/pdf, image/jpeg, or image/png. If contentType = url, the URL should point to a publicly accessible page (there should be no necessary authentication, cookies, etc.) The linked resource can be a PDF, JPG, or PNG file, but we recommend PDF for highest fidelity.
     */
    private String contentType;
    /*
     * - tag
     * One or more tags to add to the print job. You can attach a set of unique tags to a print job, and these will be available to the printer to which the print job is submitted. This feature may be useful if your application both sends and receives print jobs.
     */
    private List<String> tag;
    //
    private Gson gson = new Gson();

    public String getPrinterId() {
        return printerId;
    }

    public void setPrinterId(String printerId) {
        this.printerId = printerId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Ticket getTicket() {
        return ticket;
    }
    
    public String getTicketJSON(){
        return gson.toJson(ticket);
    }

    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

//    public String getCapabilities() {
//        return capabilities;
//    }
//
//    public void setCapabilities(String capabilities) {
//        this.capabilities = capabilities;
//    }
    public byte[] getContent() {
        return content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public List<String> getTag() {
        return tag;
    }

    public void setTag(List<String> tag) {
        this.tag = tag;
    }
}
